export enum Role {
  MANAGER,
  CONTRIBUTOR,
  VIEWER,
}
export enum TaskStatus {
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  REVIEW = "REVIEW",
  DONE = "DONE",
}
export enum Priority {
  LOW,
  NORMAL,
  HIGH,
  URGENT,
}
export enum Stage {
  PLANNING,
  DESIGN,
  DEVELOPMENT,
  TESTING,
  DEPLOYMENT,
  MAINTENANCE,
  COMPLETED,
  ON_HOLD,
  CANCELLED,
}
export enum TechStack {
  // --- Frontend ---
  NEXTJS = "NEXTJS",
  REACT = "REACT",
  TYPESCRIPT = "TYPESCRIPT",
  JAVASCRIPT = "JAVASCRIPT",
  TAILWIND_CSS = "TAILWIND_CSS",
  SHADCN_UI = "SHADCN_UI",
  REDUX = "REDUX",
  ZUSTAND = "ZUSTAND",
  VUE = "VUE",
  ANGULAR = "ANGULAR",
  SVELTE = "SVELTE",
  THREE_JS = "THREE_JS",

  // --- Backend ---
  SPRING_BOOT = "SPRING_BOOT",
  JAVA = "JAVA",
  NODEJS = "NODEJS",
  EXPRESS = "EXPRESS",
  NESTJS = "NESTJS",
  PYTHON = "PYTHON",
  DJANGO = "DJANGO",
  FLASK = "FLASK",
  GO = "GO",
  PHP = "PHP",
  LARAVEL = "LARAVEL",

  // --- Database & ORM ---
  POSTGRESQL = "POSTGRESQL",
  MONGODB = "MONGODB",
  MYSQL = "MYSQL",
  SQLITE = "SQLITE",
  REDIS = "REDIS",
  PRISMA = "PRISMA",
  DRIZZLE = "DRIZZLE",
  FIREBASE = "FIREBASE",
  SUPABASE = "SUPABASE",

  // --- DevOps & Tools ---
  DOCKER = "DOCKER",
  KUBERNETES = "KUBERNETES",
  GOOGLE_CLOUD = "GOOGLE_CLOUD",
  VERCEL = "VERCEL",
  NETLIFY = "NETLIFY",
  GIT = "GIT",
  GITHUB_ACTIONS = "GITHUB_ACTIONS",
  NGINX = "NGINX",

  // --- Mobile & Others ---
  REACT_NATIVE = "REACT_NATIVE",
  FLUTTER = "FLUTTER",
  SWIFT = "SWIFT",
  KOTLIN = "KOTLIN",
}
